/*
EXERCICIO 24 
AGRUPE NOVAMENTE OS TRABALHADORES POR DATA DE CONTRATAÇÃO;
POREM EXIBA AS DATAS QUE TEM MENOS OU 50 COLABORADORES CONTRATADOS;

*/

SELECT hire_date, COUNT(hire_date) 
AS 'Data de Contratação'
FROM employees 
GROUP BY hire_date
HAVING COUNT(hire_date) <= 50
ORDER BY COUNT(hire_date) ;