/*
EXERCICIO 5
CRIE UMA TABELA CHAMADA CADASTRO,
COM DOIS CAMPOS COMO VARCHAR, O NOME E SOBRENOME,
LIMITE OS DOIS EM 100 CARACTERES;

*/

CREATE TABLE cadastro(
nome VARCHAR (100),
sobrenome VARCHAR(100)
);