/*
O QUE SÃO FUNÇÕES?
AS FUNÇÕES SÃO BLOCOS DE CÓDIGOS JÁ DEFINIDOS QUE PODEM SER REUTILIZADOS;
ASSIM COMO A MAIORIA DAS LINGUAGENS DE PROGRAMAÇÃO JÁ POSSUEM FUNÇÕES PRONTAS,
O SQL TAMBÉM;
ELAS NOS AJUDAM A ATINGIR RESULTADOS DE FORMA SIMPLES, QUE COM APENAS QUERIES SERIAM
ATINGIDOS DE FORMA COMPLICADA;
E TAMBEM PERMITEM A REUTILIZAÇÃO DAS MESMAS;

*/