/*
EXERCICIO 29 
SELECIONE O USUÁRIO QUE TEM O SOBRENOME SMITH DA TABELA CUSTOMER
MUDE O NOME PARA MARY E O SOBRENOME PARA SMITH
REMOVER A CAIXA ALTA DE TODAS AS LETRAS, SÓ DEIXAR NAS INCIAIS
CRIE ALIAS PARA AS DUAS COLUNAS, QUE SERÁ NOME E SOBRENOME
*/

SELECT REPLACE(first_name,"MARY", "Mary") AS nome,
REPLACE(last_name,"SMITH", "Smith") AS sobrenome
FROM customer
WHERE last_name = 'SMITH';