/*
EXERCICIO 26
SELECIONE DA TABELA ADDRESS
A COLUNA ID, ADDRESS, E APLIQUE A FUNÇÃO DE CHAR_LENGTH EM
POSTALCODE
ORDENE OS DADOS DE FORMA DESCENDENTE PELO ID
*/

SELECT address_id, address,postal_code, CHAR_LENGTH(postal_code)
FROM address
ORDER BY address_id DESC;